### ISSUE TITLE
Question regarding the way precision and recall are calculated

### ISSUE THREAD

**Issue by Katya-yashenko** [alan-turing-institute/TCPDBench#16]
Hi Gertjan,

Firstly, I'd like to express my appreciation for your work on the article; it is an excellent piece of research!

I have been working with your repository and noticed that during the precision and recall calculation, specifically within the `f_measure` function in the `analysis/scripts/metrics.py` file, you ensure that 0 (the index of the first element in the timeseries) is present in both the annotations and the algorithm outputs by explicitly including it. This prompted me to consider whether this is the most appropriate approach.

While I understand that zero represents a unique case that requires special handling, it seems to me that excluding it from all sets might be a more sensible approach. The primary goal is to evaluate the performance of the algorithms in real-world applications, and in most cases, the behavior of an algorithm concerning the first point of a timeseries may not be particularly relevant.

For instance, let's consider a timeseries where the annotations indicate no changepoints other than 0. Suppose we apply an algorithm to this timeseries, and it identifies one changepoint in addition to zero. According to the current precision calculation logic, this algorithm would have a precision of 0.5 for this dataset. However, it might be more reasonable to assign a precision value of 0 in this scenario. What do you think?

**Comment by GjjvdBurg** [comment]
Hi @Katya-yashenko,

Thanks for reaching out, I'm glad to hear that you appreciate our work!

I think you raise an interesting question, let's see if I can break it down:

> While I understand that zero represents a unique case that requires special handling, it seems to me that excluding it from all sets might be a more sensible approach. The primary goal is to evaluate the performance of the algorithms in real-world applications, and in most cases, the behavior of an algorithm concerning the first point of a timeseries may not be particularly relevant.

We primarily add 0 to the set of change points to avoid the problem of the precision or recall being undefined for time series where either the algorithm or the annotator declares that a time series has no change points. It has nothing to do with the _behavior_ of the algorithm at the first point in the time series, it's done merely as a numerical convenience. 

> For instance, let's consider a timeseries where the annotations indicate no changepoints other than 0. Suppose we apply an algorithm to this timeseries, and it identifies one changepoint in addition to zero. According to the current precision calculation logic, this algorithm would have a precision of 0.5 for this dataset. However, it might be more reasonable to assign a precision value of 0 in this scenario. What do you think?

There are different solutions to handling this edge case, and indeed one of them would be to set precision to 0 in your scenario, and to 1 in the scenario where both the annotations and the algorithm declare that there are no change points (which would result in the same precision as in our approach). I think this is ultimately a matter of opinion, since mathematically the precision is simply undefined in these scenarios (similarly for the recall). 

Importantly, the choice we make would not affect the results in our paper, since we apply the same choice to all algorithms and we are more interested in how the performance of the algorithms _compare_ to one another instead of the absolute value of the metric.

I hope this answers your question, please let me know.


P.S.: You can of course always use the covering metric from our paper, which avoids this issue altogether :)
